// WASM Web Worker for rexpipe-playground.
//
// This file runs in a dedicated Web Worker context, off the main thread.
// It loads the pre-built rexpipe-wasm module from the /pkg/ static directory
// and handles processing requests via postMessage.
//
// Why a worker: the rexpipe bundle is ~1.8MB uncompressed and can take
// meaningful CPU time to parse and run on larger inputs. Keeping processing
// off the main thread ensures the UI stays responsive while the user types.
//
// WASM loading: the worker dynamically imports the glue JS module from the
// absolute path /pkg/rexpipe_wasm.js. This works because Vite serves the
// public/ directory at the root in both dev and production. We pass an
// explicit URL to the init function because inside a worker, import.meta.url
// resolves to the worker bundle, not the pkg/ directory — the default init
// behavior of computing the .wasm URL from import.meta.url would fail.

/// <reference lib="webworker" />

import type {
  ProcessRequest,
  ProcessOutcome,
  ValidatePatternResponse,
  BuiltinPatternEntry,
  SchemaResponse,
} from './types';

// Messages from main thread → worker
type WorkerRequest =
  | { type: 'process'; id: number; payload: ProcessRequest }
  | { type: 'validate'; id: number; payload: { pattern: string; flags_json: string } }
  | { type: 'schema'; id: number }
  | { type: 'builtins'; id: number };

// Messages from worker → main thread
type WorkerResponse =
  | { type: 'ready' }
  | { type: 'load-error'; message: string }
  | { type: 'process-result'; id: number; payload: ProcessOutcome }
  | { type: 'validate-result'; id: number; payload: ValidatePatternResponse }
  | { type: 'schema-result'; id: number; payload: SchemaResponse }
  | { type: 'builtins-result'; id: number; payload: BuiltinPatternEntry[] };

// The shape of the WASM glue module. Matches the .d.ts generated by wasm-pack.
interface WasmModule {
  default: (moduleOrPath?: string | URL) => Promise<unknown>;
  process_pipeline: (request_json: string) => ProcessOutcome;
  validate_pattern: (pattern: string, flags_json: string) => ValidatePatternResponse;
  list_builtins: () => BuiltinPatternEntry[];
  get_schema: () => SchemaResponse;
}

// Post a typed message to the main thread.
function post(message: WorkerResponse): void {
  (self as unknown as DedicatedWorkerGlobalScope).postMessage(message);
}

// Load the WASM module once at worker startup.
// The promise is awaited by every incoming request so that messages arriving
// before the module is ready queue up naturally.
async function loadWasm(): Promise<WasmModule> {
  // Compute the pkg/ base URL from Vite's BASE_URL env var. In dev this is
  // '/', in production (GitHub Pages) this is '/rexpipe-playground/'. The
  // same worker code works in both environments without hardcoding.
  const baseUrl: string = import.meta.env.BASE_URL ?? '/';
  const pkgPath = `${baseUrl}pkg/rexpipe_wasm.js`;
  const wasmPath = `${baseUrl}pkg/rexpipe_wasm_bg.wasm`;

  // Dynamic import from the static pkg/ path. Using `@vite-ignore` prevents
  // Vite from trying to statically analyze and rewrite this import — the
  // file lives in public/ and is not part of the module graph.
  //
  // The `/* @vite-ignore */` comment disables Vite's worker-specific import
  // analyzer, and the intermediate `string` variable prevents TypeScript from
  // trying to resolve the path at compile time. This is intentional: the WASM
  // glue file is a runtime static asset, not a build-time module.
  const module = (await import(/* @vite-ignore */ pkgPath)) as WasmModule;

  // Pass an explicit URL to init: inside a worker, import.meta.url resolves
  // to the worker bundle location, so the default init behavior (computing
  // the .wasm URL relative to import.meta.url) wouldn't find the file.
  await module.default(wasmPath);

  return module;
}

const wasmPromise: Promise<WasmModule> = (async () => {
  try {
    const wasm = await loadWasm();
    post({ type: 'ready' });
    return wasm;
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    post({ type: 'load-error', message });
    throw e;
  }
})();

// Handle incoming messages.
self.onmessage = async (event: MessageEvent<WorkerRequest>) => {
  const wasm = await wasmPromise;
  const message = event.data;

  try {
    switch (message.type) {
      case 'process': {
        const result = wasm.process_pipeline(JSON.stringify(message.payload));
        post({ type: 'process-result', id: message.id, payload: result });
        break;
      }
      case 'validate': {
        const result = wasm.validate_pattern(
          message.payload.pattern,
          message.payload.flags_json,
        );
        post({ type: 'validate-result', id: message.id, payload: result });
        break;
      }
      case 'schema': {
        post({ type: 'schema-result', id: message.id, payload: wasm.get_schema() });
        break;
      }
      case 'builtins': {
        post({ type: 'builtins-result', id: message.id, payload: wasm.list_builtins() });
        break;
      }
    }
  } catch (e) {
    // Processing errors should not kill the worker. Bubble them up as
    // a process-result with a bridge-level error shape.
    const message_str = e instanceof Error ? e.message : String(e);
    if (message.type === 'process') {
      post({
        type: 'process-result',
        id: message.id,
        payload: {
          status: 'error',
          kind: 'WorkerException',
          message: `Worker exception during processing: ${message_str}`,
          hint: null,
        },
      });
    }
    // For non-process messages, log and drop; the caller's promise will
    // time out on its own.
    console.error('[wasm-worker]', message_str);
  }
};

// Export {} to mark this file as a module (required by TS for self in workers).
export {};
